### ISSUE TITLE
在TVM中实现以下的四个函数

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/EdgeTraining#11]
- [x] conv2d
- [x] fully-connected
- [x] ReLU
- [x] Pooling

**Comment by xuxiaoqiao** [comment]
本周计划:

- 完成基本网络的训练
  - 定义交付物: 写 mnist 的测试代码
- 完成基本 Op 的 Kernel (更具体地说, 写掉 `_conv2d_grad` 的 tvm.compute()
- 完成每个 Op 的 testing

**Comment by ACA-Lab-SJTU** [comment]
其实我一直都没有一个big picture，你们的road map中各种Op是怎么计划实现的。

*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli
