### ISSUE TITLE
:sparkles:**针对NPU的激活稀疏性优化计算流图实现**:sparkles:

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/EdgeTraining#13]

**Comment by yangcyself** [comment]
请问计算流图实现是要写出FPGA嘛，还是在别的什么层面上面仿真？还是别的什么意思？

**Comment by ACA-Lab-SJTU** [comment]
不用写出FPGA，你先了解一下算子是啥。我们开会一直在讨论

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
