### ISSUE TITLE
训练过程中的Downsampling

### ISSUE THREAD

**Issue by yangcyself** [acada-sjtu/EdgeTraining#15]
在down sampling的基础上改进，加入RL的部分，使得对于每一个输入，都让RL的agent来选择downsampling的位置。
预计路线：

- [x] 设计最初版state space， action space，还有 reward function

- [ ] 在已经训好的网络上面训练RL

- [ ] 进行端到端的训练，RL和网络一起训

**Comment by ACA-Lab-SJTU** [comment]
请参考那几篇用RL来进行网络动态调整的文章，最好能找到源码，在源码基础上进行修改！
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli

**Comment by yangcyself** [comment]
这周都在探索这个issue，先需要看看我能否根据每一层feature map的输入，经过一个很小的overhead，来预测我在这个位置downsampling会导致多少精度损失，这样我在后面RL中才有可能通过feature map的简单特征决定此处是否适合做downsampling。所以目前正在做的实验是监督学习在某处做和不做downsampling带来的loss的差值。现在卡在cuda out of memory上。一开始用resnext101，后来换了一个小一点的网络resnext50 训了一会还是cuda out of memory。 
原本想把这个东西解决掉再汇报的。。。。

**Comment by yangcyself** [comment]
这周一直在

**Comment by ACA-Lab-SJTU** [comment]
晨宇，你有没有看到曹梦奇他们的论文分享？里面有相关预测方面的。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by yangcyself** [comment]
我现在的想法是：
在downSampling Point（可能做down sampling的点）加入一个用于做决策的小网络，这个网络输入当前feature map，输出几种down sampling操作的概率（比如做0.5 downsampling 和不做）（使用sigmoid 转换成概率）。实际训练的时候对于输入，按照概率选择动作。反向传递的时候，神经网络的参数还按正常的来传递，**控制器的参数可以通过sigmoid把梯度传回来**，因为一个网络输出feature map可以表示成 $$Y_{i,j} = \sum_a P(a)*avg(PoolingNeighbor(x_{i,j},a)) $$ 嘛，(a 是action) 。所以有了P（a）相乘之后就可以把梯度往回传了。

但是不知道这样的想法可行不可行，因为我往回传的梯度的意义是：这个被下采样的像素，对于我的这个输出结果有没有帮助，如果有帮助就要增大一点。可是传到下采样的控制器里面的梯度的含义好像解释不清楚，因为无法通过梯度比较出来这样的下采样方式对我的目标有没有什么帮助。
