### ISSUE TITLE
第六周文章阅读 杨晨宇 prediction based execution 和 predictive early activation

### ISSUE THREAD

**Issue by yangcyself** [acada-sjtu/EdgeTraining#17]
本周阅读文章

- [x] prediction Based Execution on Deep Neural Networks

- [x] SnaPEA: Predictive Early Activation for Reducing Computation in Deep Convolutional Neural Networks

**Comment by ACA-Lab-SJTU** [comment]
@yangcyself 把report链接分享一下，关掉issue

**Comment by yangcyself** [comment]
https://github.com/acada-sjtu/EdgeTraining/blob/master/Doc/Weekly-Report/PaperReadingNotes/SnaPEA%20Predictive%20Early%20Activation%20for%20Reducing%20Computation%20in%20Deep%20Convolutional%20Neural%20Networks%20%E8%AE%BA%E6%96%87%E9%98%85%E8%AF%BB.md

**Comment by ACA-Lab-SJTU** [comment]
close issue之前要简要小结一下进展。阅读论文的把阅读笔记的链接贴上；遇到新问题的要说明问题。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
