### ISSUE TITLE
[周任务] 完成基本 end-to-end 的训练

### ISSUE THREAD

**Issue by xuxiaoqiao** [acada-sjtu/EdgeTraining#19]
本周总体目标 **(due 周六晚)**

- [ ] 完成基本 end to end 训练。
  - [ ] 定义需要的测试case。定义如何测试代码。
    * 初步想法: 用 tinyflow.example 下的 `mnist_lenet` 测试
- [ ] 完成所有缺失的 Kernel 的 gradient (`Pool` 和 `Conv2d`) 
  - [ ] 和外界讨论。确认在 *概念* 上对这些 gradient 的运算理解没错。明确回答问题: **(due: 周四中午)**
    * 可以复制现有的 Op 吗？
  - [ ] 写出对应的 topi operator 的测试
    * 现有的 OP 是怎么测试的？怎么验证结果正确性？
    * 确认几个潜在的参考实现是否可用: `numpy/scipy`
  - [ ] 写出 topi operator 的实现
  - [ ] 把 nnvm op 做好

---
dangling tasks --- 由于这些任务耗时且优先级低，目前没有排进工作计划。但是说不定将来这些任务的优先级会提高
* 理解 nnvm graph 中每个 pass 的细节. 理解 graph 的信息
  * 好处: 在 `@reg.register_compute("conv2d_grad")` 的时候， 可以理解出 input/output 中存在哪些信息。需要 assert 哪些内容.

**Comment by ACA-Lab-SJTU** [comment]
可以和项目组里其他同学讨论。如有需要可以帮你找位ML实验室的同学

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
