### ISSUE TITLE
Maxpool2d的具体实现方案

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#20]
Maxpool2d的三种可能实现路径:
- [ ] 通过判断maxpool result和maxpool矩阵是否相等来定位grad反向传播的过程
- [ ] TVM.scan
- [ ] 将所有的maxpool_grad矩阵置零，判断每个点是否为全局最大，若是，则在改点加上对应的grad

**Comment by silentspring2** [comment]
Maxpool2d的两种可能实现路径（之前2,3合并）:
- [ ] 通过判断maxpool result和maxpool矩阵是否相等来定位grad反向传播的过程
- [ ] TVM.scan
  - [ ] TVM.scan 的官方例子是用在cumulative
  - [ ] TVM.scan 的具体操作是将X中的数据首先按照s_init进行初始化，再按照s_update进行更新，更新过程中需要s_status作为占位符，存储update过程中的中间信息
  - [ ] 我们需要的操作是判断当前点的数据是否是filter中的最大，若是，则在该点上update对应的gradient。这与下一条maxpool_grad的思路相同，两者可以合并

**Comment by silentspring2** [comment]
经过调查发现，以上两个技术路线其实是一致的。可以将当前值是否等于最大值作为判断条件，用tvm.scan来当作for循环

**Comment by ACA-Lab-SJTU** [comment]
OK

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
