### ISSUE TITLE
实现 mnist_lenet 的训练

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#21]
工作分支: dev

定义目标:
[dev 分支下的 example/mnist_lenet.py](https://github.com/silentspring2/edge-tvm/blob/dev/example/mnist_lenet.py) 可以正确运行。计算的结果无误。

-----

具体说明：
在 [mnist_lenet.py](https://github.com/silentspring2/edge-tvm/blob/dev/example/mnist_lenet.py) 中，出现了若干 Op。其中这些 Op 是没有 FGradient 实现的:
- [x] `conv2d` 的反向
  * `pad` Op 的反向情况如何?
- [x] `max_pool2d` 的反向
- [x] <del>`mean` 的反向</del>

我们的工作是:
- [x] 为单个 NNVM Op 写测试. (也可以理解为"为tvm op"写测试，反正差不多)
  - [x] 调查 NNVM 中已经有的 Op 是怎么做 testing 的
- [x] 实现 Op 反向节点的 FGradient 定义
  - [x] `NNVM_REGISTER_REDUCE_OP(mean)` 的 `FGradient` (不需要大改 tvm 下层的代码)
  - [x] `_max_pool2d_grad` 的 `FTVMCompute`
  - [x] `_conv2d_grad` 的 `FTVMCompute`
- [ ] 写端到端的测试。(优先级低于前两者)

**Comment by xuxiaoqiao** [comment]
日常update进度:

## `max_pool2d_grad` 实现状态：

### 目前（实现层面）的难点是：

1. 根据和 lfy 的讨论。在 `max_pool2d` 中, `pool_size != strides` 的情况必须考虑。
2. `tvm.compute()` API接口对 loop 的选项是比较受限的。目前只能 iterate over output tensor. 第一点和第二点同时存在，就会导致各种边界条件的细节问题，很麻烦。

### 下一步的计划是

* 方案1: 沿用目前的代码，但是强行让 `tvm.reduce_axis()` 里面变成常量。通过 boolean mask 来模拟运行时会变化的 Range()
* 方案2: 
  * 绕过 `tvm.compute()` 接口。改用 `tvm.hybrid` 方式实现 max_pool2d_grad. 
    * 这样的好处是可以自由选择 loop 方式. 所以绕过了之前的「难点2」。
    * 这样的坏处是：放弃了 tvm 中各种 scheduling 的便利设施，需要亲自研究 scheduling、fusing 等
  * 我们可以为 `max_pool2d == strides` 的特例增加一个专门的实现，这个专门的版本可以用 `tvm.compute()`，所以可以用 tvm.scheduling 相关便利设施。`tvm.hybrid` 的实现作为 fallback
* 方案三: (这个听起来高风险, 大概率不会采用) 研究为什么会报错。通过改动 tvm 下层代码的方式，让 tvm.reduce_axis() 可以接受 runtime variable (具体来说就是让外层 for-loop 的 index 可以成为内层 for-loop 的 start/end

### 同步目前状态

我目前在 `nnvm/python/nnvm/top/nn.py` 中新增了以下代码

```
@reg.register_compute("_max_pool2d_grad")
def max_pool2d_grad_compute(attrs, inputs, outs_info):
    assert attrs.get_str("layout") == "NCHW", "only NCHW layout is supported for _max_pool2d_grad"
    assert attrs.get_int_tuple("padding") == (0,0)
    stride0, stride1 = attrs.get_int_tuple("strides")
    ograd = inputs[0]
    input = inputs[1]
    output = inputs[2]
    poolsize0, poolsize1 = attrs.get_int_tuple("pool_size")  # Tuple[int, int]

    def fcompute(ni, ci, hi, wi):
        out_hstart = tvm.max(tvm.floor((hi-poolsize0+stride0)/stride0), 0)
        out_wstart = tvm.max(tvm.floor((wi-poolsize1+stride1)/stride1), 0)
        out_hend = tvm.min(tvm.floor(hi/stride0) + 1, ograd.shape[2])  # one past end
        out_wend = tvm.min(tvm.floor(wi/stride1) + 1, ograd.shape[3])  # one past end
        # out_hstart, out_hend = 0, tvm.floor(hi/stride0)
        # out_wstart, out_wend = 0, tvm.floor(wi/stride1)
        hiter = tvm.reduce_axis((out_hstart, out_hend))
        witer = tvm.reduce_axis((out_wstart, out_wend))
        is_max = input[ni, ci, hi, wi] == output[ni, ci, hiter, witer]
        return tvm.sum(ograd[ni, ci, hiter, witer], axis=[hiter, witer])

    return_val = tvm.compute(input.shape, fcompute, name="max_pool2d_grad")
    return return_val

@reg.register_schedule("_max_pool2d_grad")
def max_pool2d_grad_schedule(attrs, outs, target):
    return tvm.create_schedule(outs[0].op)
```

这么做的报错信息是

```
/Users/xuxiaoqiao/.conda/envs/tvm/bin/python /Users/xuxiaoqiao/git-repos/tvm/playground/max_pool2d_example.py
1
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/canonical.cc:47: we should not have identical entries at this point
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/arithmetic/int_set.cc:540: cannot evaluate set type Call
[22:53:02] /Users/xuxiaoqiao/git-repos/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'wi'  'hi'  does not appeared in api_args
Stack trace:
  [bt] (0) 1   libtvm.dylib                        0x000000011e138843 dmlc::LogMessageFatal::~LogMessageFatal() + 67
  [bt] (1) 2   libtvm.dylib                        0x000000011e135cd5 dmlc::LogMessageFatal::~LogMessageFatal() + 21
  [bt] (2) 3   libtvm.dylib                        0x000000011ed669f0 tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool) + 13760
  [bt] (3) 4   libtvm.dylib                        0x000000011e2b4bde tvm::ir::$_18::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 430
  [bt] (4) 5   libtvm.dylib                        0x000000011e2b4a13 decltype(std::__1::forward<tvm::ir::$_18&>(fp)(std::__1::forward<tvm::runtime::TVMArgs>(fp0), std::__1::forward<tvm::runtime::TVMRetValue*>(fp0))) std::__1::__invoke<tvm::ir::$_18&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*>(tvm::ir::$_18&&&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 115
  [bt] (5) 6   libtvm.dylib                        0x000000011e2b4977 void std::__1::__invoke_void_return_wrapper<void>::__call<tvm::ir::$_18&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*>(tvm::ir::$_18&&&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 71
  [bt] (6) 7   libtvm.dylib                        0x000000011e2b37be std::__1::__function::__func<tvm::ir::$_18, std::__1::allocator<tvm::ir::$_18>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 78
  [bt] (7) 8   libtvm.dylib                        0x000000011e2a528e std::__1::function<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 110
  [bt] (8) 9   libtvm.dylib                        0x000000011e5456f5 tvm::runtime::PackedFunc::CallPacked(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 85


libc++abi.dylib: terminating with uncaught exception of type dmlc::Error

Process finished with exit code 6
```

**Comment by silentspring2** [comment]
如果实在太麻烦，要不就先只实现pool_size = stride。
但这个问题应该会在conv2d_grad的计算的时候重新遇到（maxpool可以被conv表征）。

**Comment by xuxiaoqiao** [comment]
我看看吧。大概率会用 `tvm.hybrid` 来做了。

**Comment by ACA-Lab-SJTU** [comment]
问问郑怜悯

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by xuxiaoqiao** [comment]
日常进度 update

## `max_pool2d_grad` 实现状态

我通过之前的方案2，用 tvm.hybrid 方式实现了。目前 build 可以过，但是尚未测试。下一步的动作是：

* 想个办法做 op testing。（目前 check_function 的这个测试运行不了，因为其中有一个 to_relay 的函数调用失败了，这个原因可以理解。下一步要研究怎么解决）
* 备选方案：阅读生成的 opencl 代码，看是不是符合预期

**Comment by silentspring2** [comment]
进度update

目前正在写对单个Op的testing code。

RK3399对于TVM的default testing code报错（同样的code在XXQ的电脑上就没问题）。考虑暂时放弃直接在RK3399上开发，目前正在build虚拟机，预计今晚可以完成。

TVM对于New operator有较好的支持，可以通过nnvm.testing.check_computation完成对于单个Op的测试。该测试分为numerical和analytical两种。如果可以，最好两种都支持，因为numerical在一定情况下会莫名产生AssertionError。

**Comment by ACA-Lab-SJTU** [comment]
还是要通过测试的。check function只是其中一个可选验证步骤，还是完整测试？最终目标还是要实现反向传播的计算。中间步骤（如update，求导等）可以通过与正常（非端侧）训练过程比较验证。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by ACA-Lab-SJTU** [comment]
了解，可以现在桌面环境测试。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
check function是TVM对于新加入的单个Op进行检验的预留操作。是TVM为了开发者做的function。
尽快完成testing code主要是test driven对开发比较有目标，在完成这个时候，会撰写完整的network testing。

**Comment by ACA-Lab-SJTU** [comment]
同意。大系统开发还是要注意敏捷性。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by xuxiaoqiao** [comment]
日常进度 update

## `reduce_mean_grad` 状态

### 概括

* 我们降低了 `reduce_mean` 的 `FGradient` 实现的任务优先级 --- 也许是无限期 delay。
* 给 `reduce_mean` 做反向的工作量不是 trivial 的。
* 实现 `reduce_mean` 的反向算子这个需求不强，因为：
  * 在计算 cross_entropy 的时候，我们把 `reduce_sum` 作为 loss 就可以。这样绕开了 `mean`, 并且由于 `batch_num` 是一个 compile-time constant, 所以 `reduce_sum` 可以的确完成任务
  * 和 @silentspring2  讨论了一下，我们需要覆盖的场景对 `reduce_mean` 的反向需求不强。

### 为什么实现 `reduce_mean` 的 `FGradient` 工作量不是 trivial 的？

> 换句话说: 如果要实现 reduce_mean 的 FGradient, 需要做什么?
> [nnvm.symbol.mean API 文档](https://docs.tvm.ai/nnvm_top.html#nnvm.symbol.mean)

`mean` 接口支持对多个 axis 进行 reduce (它的 `axis` 参数可以是一个 list)。一个完整的反向实现必须支持这一点。从概念上来说，只要对被 reduce 的那几个 axis 做除法就可以了。但是从实现的层面上讲，**NNVM目前没有定义这种OP: 对一个 Tensor 的 axis=i 上的元素除以常量`length_of_axis_i`**。最接近的是对整个 Tensor 除以 scalar 常量。

所以，为了支持 `mean` 的 FGradient, 我们需要定义新的 NNVM Op, 并实现新 Op 需要的属性。这不是 trivial 的事情。

**Comment by ACA-Lab-SJTU** [comment]
第一版快速打通可以先绕过reduce mean，但绕过之后，完整的训练会有哪些问题？是否在第二版要实现？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by xuxiaoqiao** [comment]
TODO:
 - [ ] 阅读 MKLDNN/rocm 的代码，看看他们是怎么处理 `pool2d_grad` 和 `conv2d_grad` 的 scatter/gather 问题 （rocm 的更有价值）
- [ ] 对动态图相关问题，列一个调研计划

**Comment by silentspring2** [comment]
关于end2end testing，目前已经可以成功create workload（整个网络的构建以及初始化），但在执行nnvm.compiler.build()时候会产生config error报错。
今晚将于@XXQ讨论并解决这一问题

**Comment by silentspring2** [comment]
通过于@xuxiaoqiao的讨论，发现错把warning当成了error。
将继续写end2end test case。

**Comment by ACA-Lab-SJTU** [comment]
👍👍👍


-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
目前已经实现全部的前向过程（包括model和data），但在添加optimizer的过程中，会导致graph的build失败。正在研究。

**Comment by silentspring2** [comment]
发现似乎optimizer的定义会导致图的params增长，借口不匹配，因此会导致报错。
正在寻找解决方案

**Comment by ACA-Lab-SJTU** [comment]
这个改动比较大，最好能和郑怜悯，还有其他TVM的contributor商量下


-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
好的，初步猜测应该是optimizer的init中会定义params。
2h如果不能解决的话，会请求郑怜悯他们的帮助。

**Comment by ACA-Lab-SJTU** [comment]
我感觉咱们现在触及到一个核心了。设计的好会是一个重要的contribution。目前TVM是不是连inference的稀疏化也不支持？还是说生成的静态图本身就已经稀疏化了？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
据我所知应该是没有的。
静态图的优化更多是在layer fusion等层面处理，并没有碰触到layer内部的计算简化。

**Comment by ACA-Lab-SJTU** [comment]
所以这部分不仅仅是针对训练，对inference也有用。我们要好好研究一下，这可能是一个爆点。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
嗯，是的。我们目前就是想先把conv2d_sparse的inference做完；之后再添加对于_conv2d_sparse_gradient的支持。
