### ISSUE TITLE
学习MSRA关于稀疏度的工作

### ISSUE THREAD

**Issue by yangcyself** [acada-sjtu/EdgeTraining#25]
读DeepTracker_Visualizing_the_Training_Process_of_Convolutional_Neural_Networks
调查hinton的极度稀疏网络

**Comment by yangcyself** [comment]
不知道老师说的hinton极度稀疏的网络是不是这一篇
OUTRAGEOUSLY LARGE NEURAL NETWORKS:
THE SPARSELY-GATED MIXTURE-OF-EXPERTS LAYER

**Comment by ACA-Lab-SJTU** [comment]
看题目应该是这篇。关注这些极稀疏网络的训练是如何进行的？


-
Li Jiang (蒋力), Ph.D, Associate Professor,
Department of Computer Science and Engineering,
Shanghai Jiao Tong University

**Comment by yangcyself** [comment]
这个工作也可以说是极稀疏的网络，但是这个是一个**极大的**网络（像ensemble），另外网络的稀疏是conditional computing的（对于不同输入不同）。所以稀疏体现在：MOE层准备了一群超大的上千个expert，对于一个输入，选择四个结果相加，再往后传。（可能和我们之前看名字想象的稀疏不同）

Gate的**训练的过程**是把gate值加噪声，经过softmax，作为后面expert的加权，这样可以传梯度训练。

文章提出了针对这种架构的**并行方式**，其实类似map reduce，在普通网络结构进行数据并行（不同节点负责不同设备），在expert群内model并行（每一个节点负责一个expert）。

另外我在报告中提出了**新的想法**，就是把类似的模式利用到端云协同训练上，每一个端上使用和训练一小群expert，服务器负责从端收集好的expert并替换端上利用率不高的expert。这样的好处是灵活有可拓展性，可以应对数据分布不均匀的问题，以及expert的上传比上传梯度更能保护隐私。（但是也就想想开心开心吧，主要精力还是去搞down sampling）

详细报告请见：
https://github.com/acada-sjtu/EdgeTraining/blob/master/Doc/Weekly-Report/PaperReadingNotes/OUTRAGEOUSLY_LARGE_NEURAL_NETWORKS%E9%98%85%E8%AF%BB.md
