### ISSUE TITLE
Survey on ROCm and MKLdnn

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#26]
We intend to do a little survey about ROCm and MKLdnn about their implementation of conv2d/maxpool2d etc. If their implementation is useful, then we will have less work.
@xuxiaoqiao will focus on MKLdnn and I will survey the ROCm.

This survey should be finished by Thursday.

- [x] ROCm survey ([maxpool](https://shimo.im/docs/E4pBu1ZQn60bqpHJ), [conv](https://shimo.im/docs/e3sfCvxPWaY9J1a9))
- [ ] MKLDNN survey (some link)

**Comment by ACA-Lab-SJTU** [comment]
We can discuss the Scatter issue specifically on Friday. And, why always finding an “easy”? 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
蒋老师：我们寻找别的实现的原因主要是希望借鉴其在处理scatter/gather问题中所使用的公式和方法。
根据目前的调查，ROCm在处理_maxpool2d_grad时也是围绕input gradient tensor展开的，且其在判断哪些output gradient中的点会影响当前input gradient中的点方面有比较简洁、高效的实现。

**Comment by ACA-Lab-SJTU** [comment]
可以把找到的下周一/周二上午讨论一下。说不定这里我们能有所创新

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
好的

**Comment by silentspring2** [comment]
Mali的架构是Instruction Level Prallelism，ROCm的架构是Thread Level Prallelism。目前已经获得足够的信息，暂停调研。

**Comment by ACA-Lab-SJTU** [comment]
好的。
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli
