### ISSUE TITLE
细化对结构性稀疏的支持

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#28]
细化对结构性稀疏的支持：
- 在考虑控制的粒度时候，应该以硬件的最低粒度为主
- 要详细了解GPU进行运算的粒度
- 控制粒度要考虑fusing的问题

**Comment by silentspring2** [comment]
目前已经确认应该在TVM层面进行优化，NNVM层面的optimzation主要是以layer fusion为主，cuda/opencl很难one solution for all。

目前已经开始coding。

**Comment by ACA-Lab-SJTU** [comment]
好的。
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli

**Comment by silentspring2** [comment]
在TVM中重新定义了conv2d_sparse和_conv2d_sparse_gradient操作符。目前已经完成两者的接口的支持，正在通过传入的sparse matrix对两者的compute和schedule做支持。

**Comment by ACA-Lab-SJTU** [comment]
好

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
已经完成正向FTVMCompute的工作。下一步将完成反向的接口和FTVMCompute。

**Comment by ACA-Lab-SJTU** [comment]
最近效率很高啊

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
在LLVM上，目前可以以一定的sparsity节省conv2d layer的inference time。（至多减少60%）
但目前效率并不高，猜测在于并没有对数据搬运做优化。（这个将暂时放到thesis后）
下一步将确保能在RK3399上运行。需要 @xuxiaoqiao RPC部分的支持，谢谢！

**Comment by ACA-Lab-SJTU** [comment]
LLVM到RK3399么？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
LLVM是PC上的，RK3399需要opencl。刚刚有一个technical的bug在de，@xuxiaoqiao 已经帮忙解决。预期跑起来坑不大。

我对迁移到RK3399上比较乐观的原因是我们目前没有利用CPU/GPU的特性做优化，大部分的改动在于计算方法（TVMCompute），这一部分是各平台通用的。

**Comment by silentspring2** [comment]
已经成功将方法迁移到mali上，稍后会关闭降频进行测试。
目前的方法和宋卓然学姐的方法比较相似，固定n，保留1。
原因是被reshape的kernel的大小需要是编译器常量。

**Comment by ACA-Lab-SJTU** [comment]
赞，什么时候出关？
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli

**Comment by silentspring2** [comment]
正在进行测试，测试完成后开始撰写初稿。

**Comment by silentspring2** [comment]
目前进度出现了一个fallback，突然发现之前我们在RK3399上都是在用CPU在运行，猜测是RPC的问题。目前正在调试中。

**Comment by silentspring2** [comment]
原因疑似是我们之前参考的instruction就是在跑CPU的。目前正在按照怜悯所写的instruction进行调试开发。

**Comment by ACA-Lab-SJTU** [comment]
按照项目要求，CPU使用率，内存占用率要减少30%以上。最后评估指标最好也能按照这些标准来。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
好的。但有一个问题是：我们目前都是把频率lock到最大，测试最优性能，CPU的使用率可能不能很好地体现出来。
目前的状况是：
1）最终的错误大体上可以确定之前在做RPC的时候并没有配置成功，OpenCL执行在CPU，而非GPU上。会在之后去处理这一问题。我们暂时用CPU的数据代替。
2）TVM中对于常用网络的inference time的测试有一定的支持，但数据大多是fake的；我们目前首先使用这一数据（仅时间），之后如果时间允许，在截稿之前用超群学长的数据进行测试（时间+精度）。
3）之后24h最优先的问题是把反向稀疏性回路跑通。

**Comment by ACA-Lab-SJTU** [comment]
好

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
已经完成了反向回路，为了速度，目前采用的是mask的形式。
明天打算完稿。
