### ISSUE TITLE
**第四周杨晨宇任务**

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/EdgeTraining#3]
- [] 在code文件夹创建一个工作目录DownSampleTraining
- [] 选择合适的网络结构和训练数据集（最好参考文章中的选择）训练神经网络，
- [] 复现Downsampling算法

**Comment by yangcyself** [comment]
已经建立新的branch。
准备使用resnext50 作为模型，cifar100作为数据进行测试。
论文中使用了ResNeXt-d29-c08和ResNeXt-d29-c16这样的模型名称，不知道后面的编号是什么意思。

**Comment by ACA-Lab-SJTU** [comment]
可能是模型变种，你可以看看模型定义有何不同

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by yangcyself** [comment]
查了resnext原文的模型命名方法，按照那个命名法的定义，我正在测试的是resnext_d50_c32
训练并且测试完了加入down sampling的resnext模型，测试集结果从2.4GFlops 1accuracy	67.48 到 8.5GFlops 1accuracy80 基本均匀变化。和论文的曲线上相比还差一点。

**Comment by ACA-Lab-SJTU** [comment]
很好，与论文有差异是正常的，调参是门手艺活儿。继续加油。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
