### ISSUE TITLE
week 14-15 工作

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#30]
主要完成一下工作：
1.  （最重要）把CCQ学长的resnet-18重置为dense network，并在TVM上测试前向和反向，作为答辩的实验数据
1. 以下技术路线二选一完成（之后尽量都完成）：
    1.  以sparse tensor的形式输入到kernel中，确保对所有结构化稀疏算法的支持。最好能做到在dense kernel尺寸不变的情况下，以batch为单位更改数据（这一batch 13579，下一batch 246810）
    2. 更focus在layer之间的信息传递。对feature map加1 0 mask，仅传递mask=1的filter和mask本身。减少内存通信。

**Comment by silentspring2** [comment]
关于上述2.i的技术路线更新：

原本路线：把sparsity tensor设置成与weight一样的tensor，在调用nnvm.compiler.build时，作为params传入，这样sparsity tensor就作为编译器常量传入NNVM和TVM中。

路线问题：sparsity tensor的确可以作为编译器常量传入NNVM和TVM，但在NNVM_REGISTER_COMPUTE中，仅能获取到sparsity tensor的符号表示（symbolic），而我们需要在NNVM_REGISTER_COMPUTE/SCHEDULE中根据sparsity tensor的数据来做计算和调度，因此有问题。

路线更新：把sparsity tensor转换成string或matrix，与kernel_size, padding等网络结构的信息打包成Conv2DParam（新注册一个Conv2DSparseParam），这样就可以获取到sparsity tensor内部的信息。

可能风险：待定

**Comment by silentspring2** [comment]
目前经过验证opencl是在Mali上运行，在程序运行前后，Mali的占用有明显变化。
之前出现问题的原因是：
在linux对target为opencl的编译需要调用到opencl_runtime，而linux上并没有为opencl配置GPU device，因此会导致opencl warning在用CPU编程

**Comment by silentspring2** [comment]
目前resnet-18转ONNX转TVM出现了问题：
ONNX对PyTorch中一个函数的解析出现了问题，导致model的变形。正在考虑两种解决方案：
1. 手动对ONNX文件进行编辑
2. 在PyTorch里面改写函数，重新训练

个人favour方法一，因为后面要对resnet-18变成一个compact的resnet-18做操作。但是不知道对graph的输入输出操作的难度。

预计明天中午前有答案。

**Comment by silentspring2** [comment]
具体原因与link相同：
https://oldpan.me/archives/talk-about-onnx

**Comment by xuxiaoqiao** [comment]
接下来的工作计划：

1. **给出一个完整的训练演示场景** 我的计划是搭一个 resnet18 的训练网络，演示场景可能是二选一 。(a) fine tune：用一个训练好的 imagenet 网络，迁移到 fashion-mnist 并 fine tune 。或者(b)直接从头训练一个 fashion-mnist。
之前和lfy初步讨论的是偏向于a，不过b更能完整演示所有operator功能（a的fine tune 涉及op不多）。等待进一步讨论
2. **收集算子性能数据并与其他框架比较（主要是因为比 deconv）**

—-

今天和 lfy 关于 sparsity tensor 的讨论：**原则上它可以作为编译期常量、也可以不是。** 两种选择会导致工程实现上有差别。

如果希望它*不是*编译期常量，那么需要抽时间讨论 data layout 、 普通 OP 和稀疏 OP 交界时的格式转换行为定义。

目前优先级最高的是先完整实现 demo。

**Comment by silentspring2** [comment]
ResNet-18 baseline model前向已经跑通，下一步将在PyTorch中导出compact的ResNet-18 model

**Comment by silentspring2** [comment]
ResNet-18 对比结果如下：
https://github.com/acada-sjtu/EdgeTraining/blob/master/Doc/Weekly-Report/Fuyuan%20Lyu-week%2016.md

**Comment by ACA-Lab-SJTU** [comment]
还可以吧。能否看一下CPU使用率以及内存占用率的变化？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by ACA-Lab-SJTU** [comment]
baseline是在CPU上跑对吗？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
baseline是没剪枝的resnet-18，也是在Mali上跑的
我稍后把CPU的部分补一下

**Comment by ACA-Lab-SJTU** [comment]
对，与单独CPU跑也要比较。
实验室还有另外一个毕业设计也是在做TVM优化。你们到时候有对照了

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
好的

**Comment by silentspring2** [comment]
Profiling 已经完成，结果如下：
https://github.com/acada-sjtu/EdgeTraining/blob/master/Doc/Weekly-Report/Fuyuan%20Lyu-week%2016.md
