### ISSUE TITLE
ChannelWise Downsamling 的实现和测试

### ISSUE THREAD

**Issue by yangcyself** [acada-sjtu/EdgeTraining#31]
### channel wise down sampling的设想回顾
在网络的某一层中，不同channel的下采样率不一样，这样做的理由是可以进一步细粒度地节省资源，并且可能有一些channel确实不需要十分精细的信息

### 现在的进展状况
已经用pytorch实现了不同channel分别率不同的网络架构（上周），并且现在已经从小的测试网络移植到了resnext上面。

### 这周测试内容
这周将比较论文中layer wise随机下采样，和我的channel wise随机下采样，对于训练的效果，看看会不会使得训练出的网络鲁棒性增加，因为原文发现做了random downsampling可以使得网络变得鲁棒

**Comment by ACA-Lab-SJTU** [comment]
好的。请和褚超群，王晓星同学一起讨论。

-
Li Jiang (蒋力), Ph.D, Associate Professor,
Department of Computer Science and Engineering,
Shanghai Jiao Tong University
