### ISSUE TITLE
对Conv2d层前向的处理

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#35]
conv2d_sparse层需要以下几个部分：

- [x] NNVM_REGISTER_OP以及对应的Conv2DSparseParam: 主要将index flow加入到layer中
- [x] nnvm.register_compute和nnvm.register_schedule，进行断言推断和嵌套实现，调用下层TOPI算子
- [x] tvm.register_compute default实现
- [x] tvm.register_schedule default实现
- [x] tvm.register_compute mali实现
- [x] tvm.register_schedule mali实现
- [x] Debug _llvm::FCmpInst_

**Comment by silentspring2** [comment]
蒋老师您是误操作吗？

**Comment by silentspring2** [comment]
正在coding NNVM层面，NNVM_REGISTER_OP和Conv2DSparseParam大体完成，正在涉及对Conv2DSparseCorrectLayout, Conv2DSparseInferShape等判断inline函数的重写。

**Comment by silentspring2** [comment]
目前的问题卡在Conv2DSparseInferShape。其中大量的判断的数据来源于一个定义为param的参数，而我们无法获知param内的信息。需要询问XXQ。

**Comment by silentspring2** [comment]
已经初步完成NNVM REGISTER层面，正在NNVM层面嵌套实现compute和schedule

**Comment by silentspring2** [comment]
已经完成NNVM层面

**Comment by ACA-Lab-SJTU** [comment]
效率很高。
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli

**Comment by silentspring2** [comment]
在计算的时候，发现存储input index的时候，不需要以2D Tensor的形式存储，仅以1D Tensor存储即可。

原因是结构化稀疏算法不会因为N维度而不同。

**Comment by silentspring2** [comment]
- LLVM上：
通过extern的方式已初步实现default compute实现，卡在llvm的schedule中FCmpInst的error。正在调研解决方案 

- Mali上：
可以借鉴llvm default compute实现。需要额外撰写schedule部分，需要调研如何针对extern方法，实现tile and bind。

**Comment by silentspring2** [comment]
LLVM上遇到了一些奇特的error，FCmpInst做浮点数比较（用于循环判断），而理论上我们所有的循环都是基于int的。

目前正在写topi层面的测试函数，希望看看error到底是由topi还是nnvm层面引起的，以便debug

**Comment by silentspring2** [comment]
验证出来确实是topi层面函数conv2d_sparse_extern导致了FCmpInst

**Comment by silentspring2** [comment]
FCmpInst的error来源于output为Tensor list，而非单个Tensor

**Comment by ACA-Lab-SJTU** [comment]
和tensor slice类似的状况？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
似乎是两个问题，正在考虑解决方案

**Comment by silentspring2** [comment]
似乎是由于返回值为Tensor List，而非单个Tensor组成引起的

**Comment by ACA-Lab-SJTU** [comment]
看起来应该是与TVM设计初衷有相悖的地方。他们更希望用稀疏矩阵那种方式来做稀疏化？

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
目前看不出来是与TVM的设计违背，他们对于control flow+data flow的设计格式并没有任何讨论。怀疑是LLVM的解析层面出了问题。

**Comment by silentspring2** [comment]
The previous _llvm::FCmpInst_ is not caused by selecting LLVM as runtime, but by the compilation of the NNVM graph. The same error occurs while running on OpenCL.

**Comment by silentspring2** [comment]
TVM requires _target_host=llvm_ to test the network structure and dimension on the host side. That's why it generates the same error whether on OpenCL or LLVM.

**Comment by ACA-Lab-SJTU** [comment]
So we cannot avoid LLVM and its assertions? 
I think we can discuss with Huawei engineers about this problem as well. 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by ACA-Lab-SJTU** [comment]
Is it a compulsory request that the output has to be a single tensor rather than any other data structure, such as tensor list or tensor slice ...?

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
Not likely. Just discuss this with @xuxiaoqiao, there exists several Op in NNVM itself with more than one output.

**Comment by silentspring2** [comment]
Conv2d_sparse has successfully past the TVM level test on LLVM(default). This means we successfully implement the computational logic with _tvm.extern_.

NNVM level test is under progress. We need to guarantee the multi-output. Should be done before Monday.

**Comment by silentspring2** [comment]
@xuxiaoqiao Is it likely that we didn't write the FInferType correctly and it leads to the _FCmpInst_ error?

**Comment by ACA-Lab-SJTU** [comment]
Is Xiaoqiao able to see the discussion ?

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
On topi level, borrowwing some idea from topi.gather_nd, conv2d_sparse.compute can successfully express the _tensor in tensor_ case. In another word, conv2d_sparse can be expressed with tvm.compute and tvm.schedule and is not conflict with AutoTVM. 

After review, we find out that the previous error is caused by the TVM/NNVM type system. Because the NNVM _FInferType_ is not settled correctly, the index tensor is set to float32 instead of int32 and lead to the error, making us falsely believe the TVM can not handle _tensor in tensor_ expression.

I should be more careful next time!

**Comment by ACA-Lab-SJTU** [comment]
Great. This is a big step towards our ultimate goal. 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
Pass all TOPI level reference test (both OpenCL and LLVM). The only error we left is the _llvm::FCmpInst_ on NNVM level.

**Comment by silentspring2** [comment]
The _llvm: FCmpInst_ error is not likely caused by building one tensor A and the symbolic output is [A, B] since building one output out of two outputs upon _nnvm.symbol.multibox_transform_loc_ can pass the building period successfully.

**Comment by ACA-Lab-SJTU** [comment]
Fuyuan,

Would you please prepare a page of log with enough information about this bug? I’m gonna find some expert for this problem. 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
__Good News!__
The error has passed!

Thanks to @xuxiaoqiao 's reminding, I changed the _output_index_ from _kernel_index_ tensor to a tensor filled with const zero. Then the building period pass and the numerical result can be printed!

I guess the error is likely due to we did not build the _output_index_ pass and only build the _output_ pass during the test period. Maybe the _output_ pass interacts with _output_index_ pass in some unknown manner. By changing the output to a const value, we cut the interaction between these two passes and generate the result we want.

There still exists a hidden problem: Can NNVM build successfully when merging these two flows as one? This concern can only be verified once we finished the __merge__ op which merges dataflow and index-flow as one dataflow by filling the sparse part with zeros.

Some type bugs are also fixed during the process

**Comment by silentspring2** [comment]
Update:

Thanks to @xuxiaoqiao 's reminding, I use _symbol.Group()_ to pass multiple symbols to build the graph. And it passes the build period.

Once I change the _output_index_ back to input[3] (the filter index), the same error occurs again. But it can be avoided by simply create a new tensor and copy filter index.

Guess this is because of the symbolic gramma. In normal C++ or python, the function returns a copy of the data. Maybe in NNVM, the compiler is not that smart.

**Comment by ACA-Lab-SJTU** [comment]
Good to hear. Now, what happens if the index tensor contains information rather than that it is filled with const zero?

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
I define a new computation to copy information from filter index to output index. The main problem causes this error is we directly use the filter index tensor as output. I thought it will create a copy of the filter index tensor but it doesn't. That's the problem here.

**Comment by silentspring2** [comment]
All experiments have passed. This issue will be closed.
