### ISSUE TITLE
TVM中如何以一个Tensor作为另一个Tensor Compute过程中的循环变量

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#36]
在实现Conv2d Sparse前向过程中，发现需要根据Input Index(1D Tensor)对于Kernel(4D Tensor)的2nd维度进行select，即并非所有的Kernel中的2nd维度数据都会参与运算。

__要求__
如何避免在Compute中构建一个temp Tensor

__难点__
1. HalideIR对于以Tensor中的某一数据作为循环变量是否支持？Tensor在编译的时候多以Symbolic表征。
2. Tensor[Some_Tensor_Index]得到的是TensoSlice，并非想要的HalideIR Int(32)，如何转换？

**Comment by ACA-Lab-SJTU** [comment]
可以和实验室的陈子渊简单讨论一下，她毕设是我指导的，做的张量计算优化。我在想是否可以在数理领域的张量理计算范式找到一些思路。
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli

**Comment by silentspring2** [comment]
Some useful reference:
https://github.com/dmlc/tvm/issues/972
https://github.com/dmlc/tvm/issues/2606

**Comment by silentspring2** [comment]
尝试参考topi.sparse下的extern方法，backup plan是tvm.hybrid

**Comment by ACA-Lab-SJTU** [comment]
搞定了？
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli
