### ISSUE TITLE
对FC层前向的处理

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#38]
需要新增FC_sparse Op已支持indexflow+dataflow的数据格式。

经过调研发现，FC层多出现在最后若干层，且后续不再存在conv层。因此对FC的支持以indexflow+dataflow为输入，以dataflow为输出。

FC层的weight是否应该考虑稀疏性？若考虑，则存在sparse matrix相乘的问题，若不考虑，则为sparse与dense matrix相乘。

**Comment by ACA-Lab-SJTU** [comment]
FC最好也能考虑稀疏性。类似宋卓然论文中的行列稀疏。这与前面卷积image-to-col之后二维张量的处理是否一样？
-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
I will conduct a quick survey upon the structured sparsity applicable to dense op.

**Comment by silentspring2** [comment]
Based on the review, I find that it may not be a good idea to implement weight with structured sparsity. The  following is the reasons:

1.  Tile-based sparsity: the size of the tile is not determined during the compilation stage and it may vary from device to device. Hence, the requirement for the algorithms is a little bit high
2. Row-based sparsity: this method is equal to pruning one index in the output tensor. But given the fact that FC is normally used as the last layer, this may lead to the fact that always some categories will be unreachable.
3. Non-structured sparsity: How to run sparse matrix multiplication efficiently is unknown to us.

Therefore, I suggest that we just need to support structured sparse feature map times dense weight matrix. As for the implementation detail, there are two promising ways to deliver this function:
1. Transform dataflow+indexflow to a full-resolution feature map vector and reuse normal FC computation
2. Transform dataflow+indexflow to CSR format and reuse sparse FC function.

**Comment by silentspring2** [comment]
Encounter two design problems:

1. In FC layer, we take dataflow+indexflow as input. Given our feature map is structured sparsity, some column of the weight matrix will not influence the output. So we can prune these unnecessary weights temporarily to save FLOPs. But this may require the creation of a temporary tensor to store pruned weight matrix. Another way is that we expand the feature map to full length.  
2. No matter which algorithm we choose, we need to achieve the following function: Given a runtime number, determine whether it is in the index tensor.

**Comment by silentspring2** [comment]
The second problem can be solved with the following combination:
1. Create a tensor same as index tensor
2. For each value in the created tensor, compare the number to the index tensor. If the result is equal, fill the corresponding position with 1, otherwise, fill with 0
3. Sum up the created tensor. If there exists an equal pair, the sum will be 1; otherwise, the sum will be 0
4. The sum can be used as a mask.
5. If we need to determine which one in the index tensor equals to the given number, we can use argmax instead of sum to get the indice.

**Comment by ACA-Lab-SJTU** [comment]
Can we reuse the same strategy that put a bound of residual tensor after compression, and determine which columns should remain in the run time? I didn’t see any difference between the problem in FC and what we encounter in CONV. 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
Yes, it is.

The computation format of dense has similarity with the filter pruning in GEMM format. One major difference is that nodes in the output vector should not be pruned, given one node represent one class in the task of image classification.

I will write a brief report about the design of FC layer later and update here.

**Comment by ACA-Lab-SJTU** [comment]
If it’s output layer. We don’t prune it then. 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
The design report is [here](https://shimo.im/docs/q3vjvTTW993wrwhj/). The implementation details will come later.

**Comment by silentspring2** [comment]
Encounter a problem:
Given the data index, how to generate the reverse version of such data index which maps the full channel to the corresponding compact channel? 
For example, a feature map with 4 full channels has a data index [1,3], the reverse data index should be [Nan, 0, Nan, 1]?

**Comment by silentspring2** [comment]
Based on the [calculation](https://github.com/acada-sjtu/EdgeTraining/blob/master/Doc/Weekly-Report/Fuyuan%20Lyu-week%2024.md#computation-about-whether-it-benefits-a-lot-by-changing-the-dense-op), the benefit of implementing _dense_sparse_ is not worth the trouble. So we will implement _FillFM_ instead of _dense_sparse_.

**Comment by silentspring2** [comment]
This issue is close. Replacement method will be discussed in #40 .

**Comment by silentspring2** [comment]
The dense_sparse pass the LLVM TOPI reference test successfully. 

Lessons: think twice before comes to any conclusion.

**Comment by silentspring2** [comment]
dense_sparse pass NNVM build test

**Comment by silentspring2** [comment]
dense_sparse pass Mali TOPI reference test successfully.

**Comment by silentspring2** [comment]
Pass all tests, FC Layer forward pass is finished.

**Comment by ACA-Lab-SJTU** [comment]
Fantastic. What is remaining?

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
__Remains:__
Forward: Elem-wise Add/Time and BN(if the algorithm failed)
Backward: (No progress here) conv2d, dense, Elem-wise op, BN(if forward is required)

__Nextstep:__ 
Elem-wise Add/Time

**Comment by ACA-Lab-SJTU** [comment]
Does Mengqi provided enough evidence for our approach for  conv_dense and BN

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
I think so. Based on the current results, I have 90% confidence that we do not need to implement BN layer.

But to justify our assumption to the reviewers, we might need more tests under various circumstances.

**Comment by ACA-Lab-SJTU** [comment]
Chaoqun May go to Huawei Hangzhou base to carry out his Imagenet experiment for ASPLOS. They have 8 servers available, each of which contains four 1080ti card. You( mengqi)  might also go there and help. 

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by rogercmq** [comment]
了解，谢谢老师！
