### ISSUE TITLE
fill_fm Op Forward

### ISSUE THREAD

**Issue by silentspring2** [acada-sjtu/EdgeTraining#40]
It has been discussed in  #38 that the gain of implementing dense_sparse is not worth the workload. So instead of changing the computation method, we directly change the input feature map. And it is necessary to register other Op _fill_fm_. This Op will convert the data-flow + index-flow input to simple data-flow output. And the compressed part will be filled with zeros.

There are three ways to implement _fill_fm_: 
1. tvm.compute + tvm.schedule: This will leads to the gather/scatter problem. Given tvm function only support loop over output, it is not very convenient to use this way
2. tvm.hybrid: hybrid is the easiest way to implement, but we can not find any NNVM Op that uses hybrid as its backend. This way can be very risky and lacks examples.
3. tvm.extern: tvm.extern has the same expression capability as tvm.hybrid. They are both HalideIR with different wrappers. The writing gramma is more difficult but some existing Op in NNVM use tvm.extern as their backends. So this way is the most reasonable way.

And the tvm.extern implementation contains three phases:
- [x] NNVM level
- [x] TOPI on LLVM
- [ ] TOPI on Mali

**Comment by silentspring2** [comment]
NNVM level finished.

**Comment by silentspring2** [comment]
TOPI LLVM Test passed.

**Comment by silentspring2** [comment]
Encountered a strange memory error during testing on llvm. Debugging.

**Comment by silentspring2** [comment]
The memory error seems to be generated by the mismatch between our code and the tvm.codegen module. Based on our code, the tvm.codegen module generates LLVM instructions that free the same pointer twice/free a un-assigned pointer.

**Comment by silentspring2** [comment]
This repo is closed because the dense_sparse operator passed the LLVM reference test successfully. 

But the malloc error is not fixed.

**Comment by ACA-Lab-SJTU** [comment]
good

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
