### ISSUE TITLE
**端训练框架对Pytorch的支持**

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/EdgeTraining#5]
- [ ] 决定何时开始考虑
- [ ] 调研过程中要有所考虑，避免设计中导致难以向上支持

**Comment by silentspring2** [comment]
请问一下：我们所定义的Pytorch支持是对model的导入的支持吗？thanks！

**Comment by ACA-Lab-SJTU** [comment]
对。

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University

**Comment by silentspring2** [comment]
TVM对于PyTorch的支持通过ONNX转换实现。

**Comment by ACA-Lab-SJTU** [comment]
👌

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
