### ISSUE TITLE
*东岳 follow 王言治老师课题组的ADMM repo*

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/EdgeTraining#6]
- [] 请褚超群将连接共享，并从王老师他们的repo中pull一个branch下来，放在code文件夹中
- [] 请梦奇看一下他们近几年相关的剪枝工作，还有今天我在群里分享的他们ICCV的submission，请不断更新report md文档，在下次组会中分享

**Comment by rogercmq** [comment]
- [DONE] 第四周的周三到周日李东岳和我一直在扫文章，已选择了两篇可以follow的论文，都是端训练相关，一是ICLR2019的《Dynamic Channel Pruning: Feature Boosting and Suppression》，二是《DropBack: Continuous Pruning During Training》
- [TODO] 第五周周一和周二我们会看一下王老师目前的工作

**Comment by ACA-Lab-SJTU** [comment]
Great Job! Please put the important content in the md and share with us.
*******************************************
Li Jiang（蒋力）, Ph.D., Associate Professor
SEIEE-3-521, Department of Computer Science & Engineering,
Shanghai Jiaotong University, Shanghai, China
Email: jiangli@cs.sjtu.edu.cn <mailto:jiangli@cs.sjtu.edu.cn>
Web: www.cs.sjtu.edu <http://www.cs.sjtu.edu/>.cn/~jiangli

**Comment by ACA-Lab-SJTU** [comment]
@rogercmq @lidongyue12138 可以试一下代码，有什么问题问褚超群 @cqchu 。
