### ISSUE TITLE
**downsampling文章：杨晨宇**

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/EdgeTraining#7]
- [] 阅读、笔记和讲解关于Featuremap sparsity的文章NullHop: A Flexible Convolutional Neural Network Accelerator Based on Sparse Representations of Feature Maps(http://ieeexplore.ieee.org/document/8421093/)
-[] 复现起方法

**Comment by yangcyself** [comment]
已经读了并且在report文件夹里面放了总结文档，这个工作主要是关于硬件架构，请问复现的话应该是个什么思路呢？

**Comment by ACA-Lab-SJTU** [comment]
晨宇，你在report中新加了文档之后应该是可以把这个issue move on 到review中的吧。为什么我收到其他人的feedback时可以看到链接直接看新增的文档？

**Comment by ACA-Lab-SJTU** [comment]
研究一下如何实现其计算流图。因为不管是GPU还是硬件的NPU对于NNVM和TVM层面来说都是一样的。关于这一点，我给你启一个新的issue
